<?php

namespace Proxies\__CG__\Acme\DemoTwoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ModificacionesRepuesto extends \Acme\DemoTwoBundle\Entity\ModificacionesRepuesto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'id', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'idTransaccion', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'codigoAntiguo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'codigoNuevo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'nombreAntiguo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'nombreNuevo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'precioCompraAntiguo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'precioCompraNuevo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'precioVentaAntiguo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'precioVentaNuevo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'porcentajeGananciaAntiguo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'porcentajeGananciaNuevo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'cantidadAntiguo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'cantidadNuevo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'categoriaAntiguo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'categoriaNuevo');
        }

        return array('__isInitialized__', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'id', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'idTransaccion', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'codigoAntiguo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'codigoNuevo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'nombreAntiguo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'nombreNuevo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'precioCompraAntiguo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'precioCompraNuevo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'precioVentaAntiguo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'precioVentaNuevo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'porcentajeGananciaAntiguo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'porcentajeGananciaNuevo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'cantidadAntiguo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'cantidadNuevo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'categoriaAntiguo', '' . "\0" . 'Acme\\DemoTwoBundle\\Entity\\ModificacionesRepuesto' . "\0" . 'categoriaNuevo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ModificacionesRepuesto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTransaccion($idTransaccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTransaccion', array($idTransaccion));

        return parent::setIdTransaccion($idTransaccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTransaccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTransaccion', array());

        return parent::getIdTransaccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoAntiguo($codigoAntiguo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoAntiguo', array($codigoAntiguo));

        return parent::setCodigoAntiguo($codigoAntiguo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoAntiguo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoAntiguo', array());

        return parent::getCodigoAntiguo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoNuevo($codigoNuevo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoNuevo', array($codigoNuevo));

        return parent::setCodigoNuevo($codigoNuevo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoNuevo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoNuevo', array());

        return parent::getCodigoNuevo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreAntiguo($nombreAntiguo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreAntiguo', array($nombreAntiguo));

        return parent::setNombreAntiguo($nombreAntiguo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreAntiguo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreAntiguo', array());

        return parent::getNombreAntiguo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreNuevo($nombreNuevo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreNuevo', array($nombreNuevo));

        return parent::setNombreNuevo($nombreNuevo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreNuevo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreNuevo', array());

        return parent::getNombreNuevo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecioCompraAntiguo($precioCompraAntiguo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecioCompraAntiguo', array($precioCompraAntiguo));

        return parent::setPrecioCompraAntiguo($precioCompraAntiguo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecioCompraAntiguo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecioCompraAntiguo', array());

        return parent::getPrecioCompraAntiguo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecioCompraNuevo($precioCompraNuevo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecioCompraNuevo', array($precioCompraNuevo));

        return parent::setPrecioCompraNuevo($precioCompraNuevo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecioCompraNuevo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecioCompraNuevo', array());

        return parent::getPrecioCompraNuevo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecioVentaAntiguo($precioVentaAntiguo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecioVentaAntiguo', array($precioVentaAntiguo));

        return parent::setPrecioVentaAntiguo($precioVentaAntiguo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecioVentaAntiguo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecioVentaAntiguo', array());

        return parent::getPrecioVentaAntiguo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecioVentaNuevo($precioVentaNuevo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecioVentaNuevo', array($precioVentaNuevo));

        return parent::setPrecioVentaNuevo($precioVentaNuevo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecioVentaNuevo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecioVentaNuevo', array());

        return parent::getPrecioVentaNuevo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPorcentajeGananciaAntiguo($porcentajeGananciaAntiguo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPorcentajeGananciaAntiguo', array($porcentajeGananciaAntiguo));

        return parent::setPorcentajeGananciaAntiguo($porcentajeGananciaAntiguo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPorcentajeGananciaAntiguo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPorcentajeGananciaAntiguo', array());

        return parent::getPorcentajeGananciaAntiguo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPorcentajeGananciaNuevo($porcentajeGananciaNuevo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPorcentajeGananciaNuevo', array($porcentajeGananciaNuevo));

        return parent::setPorcentajeGananciaNuevo($porcentajeGananciaNuevo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPorcentajeGananciaNuevo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPorcentajeGananciaNuevo', array());

        return parent::getPorcentajeGananciaNuevo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadAntiguo($cantidadAntiguo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadAntiguo', array($cantidadAntiguo));

        return parent::setCantidadAntiguo($cantidadAntiguo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadAntiguo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadAntiguo', array());

        return parent::getCantidadAntiguo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadNuevo($cantidadNuevo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadNuevo', array($cantidadNuevo));

        return parent::setCantidadNuevo($cantidadNuevo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadNuevo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadNuevo', array());

        return parent::getCantidadNuevo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoriaAntiguo($categoriaAntiguo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoriaAntiguo', array($categoriaAntiguo));

        return parent::setCategoriaAntiguo($categoriaAntiguo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoriaAntiguo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoriaAntiguo', array());

        return parent::getCategoriaAntiguo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoriaNuevo($categoriaNuevo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoriaNuevo', array($categoriaNuevo));

        return parent::setCategoriaNuevo($categoriaNuevo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoriaNuevo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoriaNuevo', array());

        return parent::getCategoriaNuevo();
    }

}
